apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ui-chart.name" . }}
    helm.sh/chart: {{ include "ui-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      nodePort: {{ .Values.service.httpNodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ui-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
